### ISSUE TITLE
Building Footprints link redirects to cooling tower demo

### ISSUE THREAD

**Issue by CloudNiner** [geotrellis/geotrellis-site#104]
It should redirect to the building footprint elevations demo instead.

![image](https://user-images.githubusercontent.com/1818302/67210779-aacbf900-f3e7-11e9-84c6-b40c6549b951.png)

**Comment by rossbernet** [comment]
We should change this to the Building Comparison Demo rather than building footprint elevation demo:

https://demos.azavea.com/building-footprint-comparison

This building footprint elevation demo is not quite ready for sharing and it's not on https://demos.azavea.com/
