### ISSUE TITLE
Broken links on https://geotrellis.io/documentation page

### ISSUE THREAD

**Issue by CloudNiner** [geotrellis/geotrellis-site#109]
The list of links in the second section on this page respond 403 forbidden.

They should be updated to the new readthedocs hostname we migrated to awhile back.

<img width="1137" alt="Screen Shot 2020-05-21 at 11 37 07 AM" src="https://user-images.githubusercontent.com/1818302/82576486-ce127e80-9b57-11ea-9c8e-72e998171293.png">

**Comment by alexelash** [comment]
Thanks @CloudNiner. Do you know by any chance is the links below (In the Scala API Documentation section) have changed in any way?

**Comment by pomadchin** [comment]
@alexelash I'm just wondering, should it be https://geotrellis.readthedocs.io/en/latest/? 

* https://geotrellis.readthedocs.io/en/latest/tutorials/quickstart.html
* https://geotrellis.readthedocs.io/en/latest/tutorials/setup.html
* https://geotrellis.readthedocs.io/en/latest/guide/core-concepts.html

**Comment by alexelash** [comment]
@pomadchin yeah I think so! Those are the pages I recall being linked to here, guessing the URL may have changed? Thanks for gathering 'em!

**Comment by pomadchin** [comment]
@alexelash tbh I don't remember at all what was on the htpp://docs.geotrellis.io page ): mb it was a redirect? and / or mb ops have more context about it, since I thought that mb we had some local docs deployment? ¯\_(ツ)_/¯ (I tried to make this comment less useless :D)
