### ISSUE TITLE
Travelshed demo broken

### ISSUE THREAD

**Issue by kdeloach** [geotrellis/geotrellis-site#37]
![selection_053](https://cloud.githubusercontent.com/assets/43062/5944595/3dd43602-a6f6-11e4-89a9-2a5495b14523.png)

**Comment by hectcastro** [comment]
This is fixed now, but there is an [open issue](https://github.com/geotrellis/geotrellis-site/issues/38) to fix it better.

**Comment by hectcastro** [comment]
-
