### ISSUE TITLE
Move Transit and Chattanooga demos to AWS

### ISSUE THREAD

**Issue by hectcastro** [geotrellis/geotrellis-site#38]
Currently the Transit and Chattanooga demos live on separate servers. We should attempt to move them both to the `geotrellis.io` host.

**Comment by hectcastro** [comment]
These two processes are supervised by Upstart now, but are still not all on the same machine in AWS.

**Comment by fosskers** [comment]
Working on this now.

**Comment by hectcastro** [comment]
Superseded by issues in https://github.com/geotrellis/geotrellis-transit and https://github.com/geotrellis/geotrellis-chatta-demo.
