### ISSUE TITLE
Add configurable endpoints for Chattanooga and Transit demos

### ISSUE THREAD

**Issue by tnation14** [geotrellis/geotrellis-site#63]
Currently, when interacting with the "GeoTrellis in Action" carousel on https://preview.geotrellis.io, nginx routes requests to the Transit and Chattanooga services to their respective containers by name. However, now that we are working on deploying `gtsite-service`, `gt-chatta-demo` and `gt-transit` in separate ECS tasks, the Transit and Chatta endpoints will no longer be accessible by container name. The endpoints for the Chatta and Transit services should be made configurable (defaulting to `http://transit.geotrellis.com` and `http://demo.geotrellis.com/chatta/`).

**Comment by hectcastro** [comment]
Assigning to @lossyrob just so that it is on his radar. If we can get a fix for this in, we can likely replace the current geotrellis.io setup for the new one that'll deploy automatically.

Follow-up tasks will be to build out similar pipelines for Chatta and Transit so that we can later update the configured endpoints for this service to `transit.geotrellis.io` and `chatta.geotrellis.io`.

**Comment by lossyrob** [comment]
@hectcastro got it. Does it make sense to make these changes against @tnation14's PR branch for #65 ?

**Comment by hectcastro** [comment]
I don't think it matters too much if the change is scoped to the Scala project and we don't need to override the defaults with Terraform. If the service can consume something like `GT_TRANSIT_ENDPOINT` and `GT_CHATTA_ENDPOINT`, that would be great.

**Comment by lossyrob** [comment]
This sounds like a front end change, not a backend change. The requests from the client need to be changed to `transit.geotrellis.io` or `chatta.geotrellis.io`, yeah? or are we imagining that it still goes through nginx but proxies to the other subdomains? Either way unclear how this would be a scala change.

**Comment by tnation14** [comment]
I spoke to @lossyrob about this offline, and he clarified that requests to `transit` and `chatta` Are coming from the frontend JavaScript, not the Scala service. With that cleared up, we discussed a potential fix:
- Parameterize endpoints in JavaScript
- Configure `nginx` to serve a JSON file containing the URL for `chatta` and `transit` in a given environment.
    - In Staging/Production, the JSON file can be written at runtime with `cloud-init`
- Have the frontend request that file from `nginx`, and use that to set the endpoint variables for requests.
