### ISSUE TITLE
Demos lack CORS headers

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-site#90]
Because we're switching to a separate Jekyll static site, we'll need to deploy an updated version of the demos with the appropriate CORS headers

**Comment by hectcastro** [comment]
Hacky steps taken to make this happen:

- Pull current production container image down locally
- Instantiate it locally and modify the Nginx configuration so that CORS is enabled for `/gt`
- Commit the changes made to the running container image
- Push the newly modified container image to ECR
