### ISSUE TITLE
Setup GitHub Pages based deployment

### ISSUE THREAD

**Issue by hectcastro** [geotrellis/geotrellis-site#92]
- Add configuration necessary to publish site to `geotrellis.io` using GitHub Pages
- Update the associated DNS records in Route 53 for `www.geotrellis.io` and `geotrellis.io`
- Determine if revised version of site is still referencing assets or tiles produced by the existing `geotrellis.io` site
- If so, migrate existing ALB endpoint associated with `www.geotrellis.io` and `geotrellis.io` and connect it to another subdomain (e.g., `tiles.geotrellis.io`)
- Update the existing Jekyll site to retrieve assets and tiles from `tiles.geotrellis.io`

**Comment by rbreslow** [comment]
I completed everything above, with the addition of:

- Update default repository branch to `master`
- Remove stale (diverged from changes made from GitHub UI) `develop` branch

https://geotrellis.io 🎉
