### ISSUE TITLE
URL for documentation is inconsistent

### ISSUE THREAD

**Issue by rbreslow** [geotrellis/geotrellis-site#94]
![image](https://user-images.githubusercontent.com/1774125/62890661-eb393780-bd11-11e9-8d86-a4ab46b85e43.png)

- If you click **Go To Docs**, you get https://geotrellis.readthedocs.io/en/latest/.
- If you click **Core Concepts**, you get https://docs.geotrellis.io/en/latest/guide/core-concepts.html.

**Comment by alexelash** [comment]
Will note for future, but closing for now as the differing base slug doesn't affect the user's experience.
