### ISSUE TITLE
Possible button drop shadow inconsistencies

### ISSUE THREAD

**Issue by rbreslow** [geotrellis/geotrellis-site#95]
![image](https://user-images.githubusercontent.com/1774125/62890947-88946b80-bd12-11e9-9751-acbbd86d32fc.png)

vs.

![image](https://user-images.githubusercontent.com/1774125/62890959-8f22e300-bd12-11e9-8a35-136443e3e7db.png)

**Comment by alexelash** [comment]
Closing as both buttons do have a dropshadow:
![Screen Shot 2019-08-14 at 2 08 47 PM](https://user-images.githubusercontent.com/5672295/63044912-3cc1fd80-be9d-11e9-9768-4b7051c0dd72.png)

![Screen Shot 2019-08-14 at 2 09 13 PM](https://user-images.githubusercontent.com/5672295/63044874-23b94c80-be9d-11e9-973c-26fb717cf797.png)
