### ISSUE TITLE
Add Eclipse and/or LocationTech info to footer

### ISSUE THREAD

**Issue by rcheetham** [geotrellis/geotrellis-site#98]
Because the Eclipse Foundation owns the GeoTrellis trademark, we must identify GeoTrellis as a LocationTech and/or Eclipse Foundation project. We need to at least include text to this effect in our footer. An example of this is at https://www.geomesa.org/

Related to #22

**Comment by alexelash** [comment]
Addressed in #101 — Per [Ross's comment,](https://github.com/geotrellis/geotrellis-site/pull/101#issuecomment-522622386) we can revisit if we need to add logos here.
